import { MigrationInterface, QueryRunner } from "typeorm";

export class migration1679586848886 implements MigrationInterface {
    name = 'migration1679586848886'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "core_department" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "code" character varying(50) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dca80ecb4a8f22d93da4c5b9842" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_module" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_295e82005d715e8c084576820ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_menu" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "tag" character varying(150) NOT NULL, "order_menu" integer NOT NULL, "icon_class" character varying(45), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "module_id" integer, CONSTRAINT "PK_d6c1892c7896ced5307d5b791c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_de52081236131e06645a2c828d" ON "core_menu" ("module_id") `);
        await queryRunner.query(`CREATE TABLE "core_privilege" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(250) NOT NULL, "tag" character varying(100) NOT NULL, "path_accion" character varying(200), "path_menu" character varying(45), "is_menu_option" boolean NOT NULL DEFAULT false, "order" integer, "icon_class" character varying(45), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "menu_id" integer, CONSTRAINT "PK_a1aefe843478c130e8f23fe5099" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e8c8998255f455bbf2dd08cf1f" ON "core_privilege" ("menu_id") `);
        await queryRunner.query(`CREATE TABLE "core_privilege_category" ("id" SERIAL NOT NULL, "name" character varying(120) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5492f7d5f939ca3ba7d97566aa7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_profile" ("id" SERIAL NOT NULL, "name" character varying(45) NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "department_id" integer, CONSTRAINT "PK_1754d97e5debda72077e99fbc50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ae3739407c49a5c8809e4884a1" ON "core_profile" ("department_id") `);
        await queryRunner.query(`CREATE TABLE "core_gender" ("id" SERIAL NOT NULL, "name" character varying(45) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cc40e16c95f72313d5e960d5dd6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_nationality" ("id" SERIAL NOT NULL, "name" character varying(45) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_36104d91684d969789f17bda09e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_person_type" ("id" SERIAL NOT NULL, "name" character varying(45) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7baa775c2ac72dde00d05b9893f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_person" ("id" SERIAL NOT NULL, "linkedin" character varying(100), "run" character varying(12) NOT NULL, "names" character varying(100) NOT NULL, "last_names" character varying(100) NOT NULL, "address" character varying(150), "personal_phone" character varying(50), "mobile_phone" character varying(50), "birthday" date NOT NULL, "city" character varying(50), "about_me" text, "employee_id" uuid, "gender_id" integer, "nationality_id" integer, CONSTRAINT "UQ_c69a951ac81fb1b7f696c791188" UNIQUE ("run"), CONSTRAINT "REL_2aa54ea7bef00a031bda873433" UNIQUE ("employee_id"), CONSTRAINT "PK_890c80896864293121ac08a44af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2aa54ea7bef00a031bda873433" ON "core_person" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_acdf15c5cb71548307422413a8" ON "core_person" ("gender_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_726180cd48aff0f9b1bcf7aa38" ON "core_person" ("nationality_id") `);
        await queryRunner.query(`CREATE TABLE "core_category_position" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f6324e3ff1047ccc8c55a74d60d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_position" ("id" SERIAL NOT NULL, "name" character varying(45) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "category_position_id" integer, CONSTRAINT "PK_929e0fc93de1654a9428acecc77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c3356203ad93710f48965f2581" ON "core_position" ("category_position_id") `);
        await queryRunner.query(`CREATE TABLE "core_service_employee" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_af3be55a6dccf6223c8d29e78a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_employee" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nickname" character varying(45) NOT NULL, "email" character varying(50) NOT NULL, "image" character varying(50) NOT NULL, "discord_account" character varying(100) NOT NULL, "discord_id" character varying(100), "jira_id" character varying(100), "is_active" boolean NOT NULL DEFAULT true, "last_login" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "position_id" integer, "service_employee_id" integer, CONSTRAINT "REL_e1fa7a6dfde679c9ed7d6e05e2" UNIQUE ("service_employee_id"), CONSTRAINT "PK_ac7609a83c8f14b141d9c8ca05c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1c80bd671a263e9bd0b60f9d78" ON "core_employee" ("position_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1fa7a6dfde679c9ed7d6e05e2" ON "core_employee" ("service_employee_id") `);
        await queryRunner.query(`CREATE TABLE "core_employee_profile" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "employee_id" uuid, "profile_id" integer, CONSTRAINT "UQ_f0266e29c72de74c040b791884c" UNIQUE ("employee_id", "profile_id"), CONSTRAINT "PK_8d027b883f9b07f627e360e3b81" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_employee_technology" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "employee_id" uuid, "technology_id" integer, CONSTRAINT "UQ_9d1bed57121c121f029cde31f92" UNIQUE ("employee_id", "technology_id"), CONSTRAINT "PK_a6133e78feb3b3d342afb763383" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_technology" ("id" SERIAL NOT NULL, "name" character varying(150), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "category_id" integer, CONSTRAINT "PK_518261e09bc91e03e900eeaea3f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eb48379b344f1da869e033cf65" ON "core_technology" ("category_id") `);
        await queryRunner.query(`CREATE TABLE "core_category_technology" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_53d09be0db74b8340832621680f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_categories" ("id" SERIAL NOT NULL, "requerimentType" character varying(160) NOT NULL, "anticipationDays" integer NOT NULL, "resolutionTime" integer NOT NULL, CONSTRAINT "PK_2cddd8f98a564fc1d3530628f29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_phrases" ("id" SERIAL NOT NULL, "name" character varying(160) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cf86dc1b6d80b74864ea786f14a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_department_module" ("department_id" integer NOT NULL, "module_id" integer NOT NULL, CONSTRAINT "PK_70537e966488e73d1711e6ce5c6" PRIMARY KEY ("department_id", "module_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cf8cc699a0f9025156982419c2" ON "core_department_module" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_59f154505e41ee67c44d47d83c" ON "core_department_module" ("module_id") `);
        await queryRunner.query(`CREATE TABLE "core_privilege_category_privilege" ("privilege_category_id" integer NOT NULL, "privilege_id" integer NOT NULL, CONSTRAINT "PK_041399f0c60aaa43992bdc268d8" PRIMARY KEY ("privilege_category_id", "privilege_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_09d9a0f69410d026ccf1ed092d" ON "core_privilege_category_privilege" ("privilege_category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0f05092a88d68fe4f650188f3" ON "core_privilege_category_privilege" ("privilege_id") `);
        await queryRunner.query(`CREATE TABLE "core_profile_privilege" ("profile_id" integer NOT NULL, "privilege_id" integer NOT NULL, CONSTRAINT "PK_1ea5abc39e79dac07fec6fd90a4" PRIMARY KEY ("profile_id", "privilege_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6a232c95d71d5046567addfc0a" ON "core_profile_privilege" ("profile_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc9c6414751440288ca1dec5e3" ON "core_profile_privilege" ("privilege_id") `);
        await queryRunner.query(`ALTER TABLE "core_menu" ADD CONSTRAINT "FK_de52081236131e06645a2c828d7" FOREIGN KEY ("module_id") REFERENCES "core_module"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_privilege" ADD CONSTRAINT "FK_e8c8998255f455bbf2dd08cf1f8" FOREIGN KEY ("menu_id") REFERENCES "core_menu"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_profile" ADD CONSTRAINT "FK_ae3739407c49a5c8809e4884a19" FOREIGN KEY ("department_id") REFERENCES "core_department"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_person" ADD CONSTRAINT "FK_2aa54ea7bef00a031bda873433e" FOREIGN KEY ("employee_id") REFERENCES "core_employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_person" ADD CONSTRAINT "FK_acdf15c5cb71548307422413a81" FOREIGN KEY ("gender_id") REFERENCES "core_gender"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_person" ADD CONSTRAINT "FK_726180cd48aff0f9b1bcf7aa38f" FOREIGN KEY ("nationality_id") REFERENCES "core_nationality"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_position" ADD CONSTRAINT "FK_c3356203ad93710f48965f25813" FOREIGN KEY ("category_position_id") REFERENCES "core_category_position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_employee" ADD CONSTRAINT "FK_1c80bd671a263e9bd0b60f9d785" FOREIGN KEY ("position_id") REFERENCES "core_position"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_employee" ADD CONSTRAINT "FK_e1fa7a6dfde679c9ed7d6e05e23" FOREIGN KEY ("service_employee_id") REFERENCES "core_service_employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_employee_profile" ADD CONSTRAINT "FK_ad9eb8a67df9df5f78e87d48103" FOREIGN KEY ("employee_id") REFERENCES "core_employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_employee_profile" ADD CONSTRAINT "FK_937bbd29cf5432b48b0aaf9f635" FOREIGN KEY ("profile_id") REFERENCES "core_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_employee_technology" ADD CONSTRAINT "FK_03047882c46b25db917dad28437" FOREIGN KEY ("employee_id") REFERENCES "core_employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_employee_technology" ADD CONSTRAINT "FK_f1e0cd1557824206c58a6288b26" FOREIGN KEY ("technology_id") REFERENCES "core_technology"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_technology" ADD CONSTRAINT "FK_eb48379b344f1da869e033cf659" FOREIGN KEY ("category_id") REFERENCES "core_category_technology"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_department_module" ADD CONSTRAINT "FK_cf8cc699a0f9025156982419c2d" FOREIGN KEY ("department_id") REFERENCES "core_department"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "core_department_module" ADD CONSTRAINT "FK_59f154505e41ee67c44d47d83c9" FOREIGN KEY ("module_id") REFERENCES "core_module"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_privilege_category_privilege" ADD CONSTRAINT "FK_09d9a0f69410d026ccf1ed092d0" FOREIGN KEY ("privilege_category_id") REFERENCES "core_privilege_category"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "core_privilege_category_privilege" ADD CONSTRAINT "FK_b0f05092a88d68fe4f650188f3e" FOREIGN KEY ("privilege_id") REFERENCES "core_privilege"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_profile_privilege" ADD CONSTRAINT "FK_6a232c95d71d5046567addfc0a7" FOREIGN KEY ("profile_id") REFERENCES "core_profile"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "core_profile_privilege" ADD CONSTRAINT "FK_dc9c6414751440288ca1dec5e3e" FOREIGN KEY ("privilege_id") REFERENCES "core_privilege"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "core_profile_privilege" DROP CONSTRAINT "FK_dc9c6414751440288ca1dec5e3e"`);
        await queryRunner.query(`ALTER TABLE "core_profile_privilege" DROP CONSTRAINT "FK_6a232c95d71d5046567addfc0a7"`);
        await queryRunner.query(`ALTER TABLE "core_privilege_category_privilege" DROP CONSTRAINT "FK_b0f05092a88d68fe4f650188f3e"`);
        await queryRunner.query(`ALTER TABLE "core_privilege_category_privilege" DROP CONSTRAINT "FK_09d9a0f69410d026ccf1ed092d0"`);
        await queryRunner.query(`ALTER TABLE "core_department_module" DROP CONSTRAINT "FK_59f154505e41ee67c44d47d83c9"`);
        await queryRunner.query(`ALTER TABLE "core_department_module" DROP CONSTRAINT "FK_cf8cc699a0f9025156982419c2d"`);
        await queryRunner.query(`ALTER TABLE "core_technology" DROP CONSTRAINT "FK_eb48379b344f1da869e033cf659"`);
        await queryRunner.query(`ALTER TABLE "core_employee_technology" DROP CONSTRAINT "FK_f1e0cd1557824206c58a6288b26"`);
        await queryRunner.query(`ALTER TABLE "core_employee_technology" DROP CONSTRAINT "FK_03047882c46b25db917dad28437"`);
        await queryRunner.query(`ALTER TABLE "core_employee_profile" DROP CONSTRAINT "FK_937bbd29cf5432b48b0aaf9f635"`);
        await queryRunner.query(`ALTER TABLE "core_employee_profile" DROP CONSTRAINT "FK_ad9eb8a67df9df5f78e87d48103"`);
        await queryRunner.query(`ALTER TABLE "core_employee" DROP CONSTRAINT "FK_e1fa7a6dfde679c9ed7d6e05e23"`);
        await queryRunner.query(`ALTER TABLE "core_employee" DROP CONSTRAINT "FK_1c80bd671a263e9bd0b60f9d785"`);
        await queryRunner.query(`ALTER TABLE "core_position" DROP CONSTRAINT "FK_c3356203ad93710f48965f25813"`);
        await queryRunner.query(`ALTER TABLE "core_person" DROP CONSTRAINT "FK_726180cd48aff0f9b1bcf7aa38f"`);
        await queryRunner.query(`ALTER TABLE "core_person" DROP CONSTRAINT "FK_acdf15c5cb71548307422413a81"`);
        await queryRunner.query(`ALTER TABLE "core_person" DROP CONSTRAINT "FK_2aa54ea7bef00a031bda873433e"`);
        await queryRunner.query(`ALTER TABLE "core_profile" DROP CONSTRAINT "FK_ae3739407c49a5c8809e4884a19"`);
        await queryRunner.query(`ALTER TABLE "core_privilege" DROP CONSTRAINT "FK_e8c8998255f455bbf2dd08cf1f8"`);
        await queryRunner.query(`ALTER TABLE "core_menu" DROP CONSTRAINT "FK_de52081236131e06645a2c828d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc9c6414751440288ca1dec5e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a232c95d71d5046567addfc0a"`);
        await queryRunner.query(`DROP TABLE "core_profile_privilege"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0f05092a88d68fe4f650188f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09d9a0f69410d026ccf1ed092d"`);
        await queryRunner.query(`DROP TABLE "core_privilege_category_privilege"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59f154505e41ee67c44d47d83c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf8cc699a0f9025156982419c2"`);
        await queryRunner.query(`DROP TABLE "core_department_module"`);
        await queryRunner.query(`DROP TABLE "core_phrases"`);
        await queryRunner.query(`DROP TABLE "core_categories"`);
        await queryRunner.query(`DROP TABLE "core_category_technology"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb48379b344f1da869e033cf65"`);
        await queryRunner.query(`DROP TABLE "core_technology"`);
        await queryRunner.query(`DROP TABLE "core_employee_technology"`);
        await queryRunner.query(`DROP TABLE "core_employee_profile"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1fa7a6dfde679c9ed7d6e05e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c80bd671a263e9bd0b60f9d78"`);
        await queryRunner.query(`DROP TABLE "core_employee"`);
        await queryRunner.query(`DROP TABLE "core_service_employee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3356203ad93710f48965f2581"`);
        await queryRunner.query(`DROP TABLE "core_position"`);
        await queryRunner.query(`DROP TABLE "core_category_position"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_726180cd48aff0f9b1bcf7aa38"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_acdf15c5cb71548307422413a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2aa54ea7bef00a031bda873433"`);
        await queryRunner.query(`DROP TABLE "core_person"`);
        await queryRunner.query(`DROP TABLE "core_person_type"`);
        await queryRunner.query(`DROP TABLE "core_nationality"`);
        await queryRunner.query(`DROP TABLE "core_gender"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae3739407c49a5c8809e4884a1"`);
        await queryRunner.query(`DROP TABLE "core_profile"`);
        await queryRunner.query(`DROP TABLE "core_privilege_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8c8998255f455bbf2dd08cf1f"`);
        await queryRunner.query(`DROP TABLE "core_privilege"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de52081236131e06645a2c828d"`);
        await queryRunner.query(`DROP TABLE "core_menu"`);
        await queryRunner.query(`DROP TABLE "core_module"`);
        await queryRunner.query(`DROP TABLE "core_department"`);
    }

}
